<template>
    <div class="flex flex-wrap gap-12 ">
       <AppIcon name="Activity" size="60" color="#85f29f" />
        <AppIcon name="Airplay" size="40" color="#85f29f" />
        <AppIcon name="AlarmClock" size="40" color="#85f29f" />
        <AppIcon name="AlertCircle" size="40" color="#85f29f" />
        <AppIcon name="AlertOctagon" size="40" color="#85f29f" />
        <AppIcon name="AlertTriangle" size="40" color="#85f29f" />
        <AppIcon name="AlignCenter" size="40" color="#85f29f" />
        <AppIcon name="AlignJustify" size="40" color="#85f29f" />
        <AppIcon name="AlignLeft" size="40" color="#85f29f" />
        <AppIcon name="AlignRight" size="40" color="#85f29f" />
        <AppIcon name="Anchor" size="40" color="#85f29f" />
        <AppIcon name="Aperture" size="40" color="#85f29f" />
        <AppIcon name="Archive" size="40" color="#85f29f" />
        <AppIcon name="ArrowDown" size="40" color="#85f29f" />
        <AppIcon name="ArrowDownCircle" size="40" color="#85f29f" />
        <AppIcon name="ArrowDownLeft" size="40" color="#85f29f" />
        <AppIcon name="ArrowDownRight" size="40" color="#85f29f" />
        <AppIcon name="ArrowLeft" size="40" color="#85f29f" />
        <AppIcon name="ArrowLeftCircle" size="40" color="#85f29f" />
        <AppIcon name="ArrowRight" size="40" color="#85f29f" />
        <AppIcon name="ArrowRightCircle" size="40" color="#85f29f" />
        <AppIcon name="ArrowUp" size="40" color="#85f29f" />
        <AppIcon name="ArrowUpCircle" size="40" color="#85f29f" />
        <AppIcon name="ArrowUpLeft" size="40" color="#85f29f" />
        <AppIcon name="ArrowUpRight" size="40" color="#85f29f" />
        <AppIcon name="AtSign" size="40" color="#85f29f" />
        <AppIcon name="Award" size="40" color="#85f29f" />
        <AppIcon name="BarChart" size="40" color="#85f29f" />
        <AppIcon name="BarChart2" size="40" color="#85f29f" />
        <AppIcon name="Battery" size="40" color="#85f29f" />
        <AppIcon name="BatteryCharging" size="40" color="#85f29f" />
        <AppIcon name="Bell" size="40" color="#85f29f" />
        <AppIcon name="BellOff" size="40" color="#85f29f" />
        <AppIcon name="Bluetooth" size="40" color="#85f29f" />
        <AppIcon name="Bold" size="40" color="#85f29f" />
        <AppIcon name="Book" size="40" color="#85f29f" />
        <AppIcon name="BookOpen" size="40" color="#85f29f" />
        <AppIcon name="Bookmark" size="40" color="#85f29f" />
        <AppIcon name="Box" size="40" color="#85f29f" />
        <AppIcon name="Briefcase" size="40" color="#85f29f" />
        <AppIcon name="Calendar" size="40" color="#85f29f" />
        <AppIcon name="Camera" size="40" color="#85f29f" />
        <AppIcon name="CameraOff" size="40" color="#85f29f" />
        <AppIcon name="Cast" size="40" color="#85f29f" />
        <AppIcon name="Check" size="40" color="#85f29f" />
        <AppIcon name="CheckCircle" size="40" color="#85f29f" />
        <AppIcon name="CheckSquare" size="40" color="#85f29f" />
        <AppIcon name="ChevronDown" size="40" color="#85f29f" />
        <AppIcon name="ChevronLeft" size="40" color="#85f29f" />
        <AppIcon name="ChevronRight" size="40" color="#85f29f" />
        <AppIcon name="ChevronUp" size="40" color="#85f29f" />
        <AppIcon name="ChevronsDown" size="40" color="#85f29f" />
        <AppIcon name="ChevronsLeft" size="40" color="#85f29f" />
        <AppIcon name="ChevronsRight" size="40" color="#85f29f" />
        <AppIcon name="ChevronsUp" size="40" color="#85f29f" />
        <AppIcon name="Chrome" size="40" color="#85f29f" />
        <AppIcon name="Circle" size="40" color="#85f29f" />
        <AppIcon name="Clipboard" size="40" color="#85f29f" />
        <AppIcon name="Clock" size="40" color="#85f29f" />
        <AppIcon name="Cloud" size="40" color="#85f29f" />
        <AppIcon name="CloudDrizzle" size="40" color="#85f29f" />
        <AppIcon name="CloudLightning" size="40" color="#85f29f" />
        <AppIcon name="CloudOff" size="40" color="#85f29f" />
        <AppIcon name="CloudRain" size="40" color="#85f29f" />
        <AppIcon name="CloudSnow" size="40" color="#85f29f" />
        <AppIcon name="Code" size="40" color="#85f29f" />
        <AppIcon name="Codepen" size="40" color="#85f29f" />
        <AppIcon name="Coffee" size="40" color="#85f29f" />
        <AppIcon name="Command" size="40" color="#85f29f" />
        <AppIcon name="Compass" size="40" color="#85f29f" />
        <AppIcon name="Copy" size="40" color="#85f29f" />
        <AppIcon name="CornerDownLeft" size="40" color="#85f29f" />
        <AppIcon name="CornerDownRight" size="40" color="#85f29f" />
        <AppIcon name="CornerLeftDown" size="40" color="#85f29f" />
        <AppIcon name="CornerLeftUp" size="40" color="#85f29f" />
        <AppIcon name="CornerRightDown" size="40" color="#85f29f" />
        <AppIcon name="CornerRightUp" size="40" color="#85f29f" />
        <AppIcon name="CornerUpLeft" size="40" color="#85f29f" />
        <AppIcon name="CornerUpRight" size="40" color="#85f29f" />
        <AppIcon name="Cpu" size="40" color="#85f29f" />
        <AppIcon name="CreditCard" size="40" color="#85f29f" />
        <AppIcon name="Crop" size="40" color="#85f29f" />
        <AppIcon name="Crosshair" size="40" color="#85f29f" />
        <AppIcon name="Database" size="40" color="#85f29f" />
        <AppIcon name="Delete" size="40" color="#85f29f" />
        <AppIcon name="Disc" size="40" color="#85f29f" />
        <AppIcon name="DollarSign" size="40" color="#85f29f" />
        <AppIcon name="Download" size="40" color="#85f29f" />
        <AppIcon name="DownloadCloud" size="40" color="#85f29f" />
        <AppIcon name="Droplet" size="40" color="#85f29f" />
        <AppIcon name="Edit" size="40" color="#85f29f" />
        <AppIcon name="Edit2" size="40" color="#85f29f" />
        <AppIcon name="Edit3" size="40" color="#85f29f" />
        <AppIcon name="ExternalLink" size="40" color="#85f29f" />
        <AppIcon name="Eye" size="40" color="#85f29f" />
        <AppIcon name="EyeOff" size="40" color="#85f29f" />
        <AppIcon name="Facebook" size="40" color="#85f29f" />
        <AppIcon name="FastForward" size="40" color="#85f29f" />
        <AppIcon name="Feather" size="40" color="#85f29f" />
        <AppIcon name="File" size="40" color="#85f29f" />
        <AppIcon name="FileMinus" size="40" color="#85f29f" />
        <AppIcon name="FilePlus" size="40" color="#85f29f" />
        <AppIcon name="FileText" size="40" color="#85f29f" />
        <AppIcon name="Film" size="40" color="#85f29f" />
        <AppIcon name="Filter" size="40" color="#85f29f" />
        <AppIcon name="Flag" size="40" color="#85f29f" />
        <AppIcon name="Folder" size="40" color="#85f29f" />
        <AppIcon name="FolderMinus" size="40" color="#85f29f" />
        <AppIcon name="FolderPlus" size="40" color="#85f29f" />
        <AppIcon name="Gift" size="40" color="#85f29f" />
        <AppIcon name="GitBranch" size="40" color="#85f29f" />
        <AppIcon name="GitCommit" size="40" color="#85f29f" />
        <AppIcon name="GitMerge" size="40" color="#85f29f" />
        <AppIcon name="GitPullRequest" size="40" color="#85f29f" />
        <AppIcon name="Github" size="40" color="#85f29f" />
        <AppIcon name="Gitlab" size="40" color="#85f29f" />
        <AppIcon name="Globe" size="40" color="#85f29f" />
        <AppIcon name="Grid" size="40" color="#85f29f" />
        <AppIcon name="HardDrive" size="40" color="#85f29f" />
        <AppIcon name="Hash" size="40" color="#85f29f" />
        <AppIcon name="Headphones" size="40" color="#85f29f" />
        <AppIcon name="Heart" size="40" color="#85f29f" />
        <AppIcon name="HelpCircle" size="40" color="#85f29f" />
        <AppIcon name="Home" size="40" color="#85f29f" />
        <AppIcon name="Image" size="40" color="#85f29f" />
        <AppIcon name="Inbox" size="40" color="#85f29f" />
        <AppIcon name="Info" size="40" color="#85f29f" />
        <AppIcon name="Instagram" size="40" color="#85f29f" />
        <AppIcon name="Italic" size="40" color="#85f29f" />
        <AppIcon name="Layers" size="40" color="#85f29f" />
        <AppIcon name="Layout" size="40" color="#85f29f" />
        <AppIcon name="LifeBuoy" size="40" color="#85f29f" />
        <AppIcon name="Link" size="40" color="#85f29f" />
        <AppIcon name="Link2" size="40" color="#85f29f" />
        <AppIcon name="Linkedin" size="40" color="#85f29f" />
        <AppIcon name="List" size="40" color="#85f29f" />
        <AppIcon name="Loader" size="40" color="#85f29f" />
        <AppIcon name="Lock" size="40" color="#85f29f" />
        <AppIcon name="LogIn" size="40" color="#85f29f" />
        <AppIcon name="LogOut" size="40" color="#85f29f" />
        <AppIcon name="Mail" size="40" color="#85f29f" />
        <AppIcon name="Map" size="40" color="#85f29f" />
        <AppIcon name="MapPin" size="40" color="#85f29f" />
        <AppIcon name="Maximize" size="40" color="#85f29f" />
        <AppIcon name="Maximize2" size="40" color="#85f29f" />
        <AppIcon name="Meh" size="40" color="#85f29f" />
        <AppIcon name="Menu" size="40" color="#85f29f" />
        <AppIcon name="MessageCircle" size="40" color="#85f29f" />
        <AppIcon name="MessageSquare" size="40" color="#85f29f" />
        <AppIcon name="Mic" size="40" color="#85f29f" />
        <AppIcon name="MicOff" size="40" color="#85f29f" />
        <AppIcon name="Minimize" size="40" color="#85f29f" />
        <AppIcon name="Minimize2" size="40" color="#85f29f" />
        <AppIcon name="Minus" size="40" color="#85f29f" />
        <AppIcon name="MinusCircle" size="40" color="#85f29f" />
        <AppIcon name="MinusSquare" size="40" color="#85f29f" />
        <AppIcon name="Monitor" size="40" color="#85f29f" />
        <AppIcon name="Moon" size="40" color="#85f29f" />
        <AppIcon name="MoreHorizontal" size="40" color="#85f29f" />
        <AppIcon name="MoreVertical" size="40" color="#85f29f" />
        <AppIcon name="MousePointer" size="40" color="#85f29f" />
        <AppIcon name="Move" size="40" color="#85f29f" />
        <AppIcon name="Music" size="40" color="#85f29f" />
        <AppIcon name="Navigation" size="40" color="#85f29f" />
        <AppIcon name="Navigation2" size="40" color="#85f29f" />
        <AppIcon name="Octagon" size="40" color="#85f29f" />
        <AppIcon name="Package" size="40" color="#85f29f" />
        <AppIcon name="Paperclip" size="40" color="#85f29f" />
        <AppIcon name="Pause" size="40" color="#85f29f" />
        <AppIcon name="PauseCircle" size="40" color="#85f29f" />
        <AppIcon name="PenTool" size="40" color="#85f29f" />
        <AppIcon name="Percent" size="40" color="#85f29f" />
        <AppIcon name="Phone" size="40" color="#85f29f" />
        <AppIcon name="PhoneCall" size="40" color="#85f29f" />
        <AppIcon name="PhoneForwarded" size="40" color="#85f29f" />
        <AppIcon name="PhoneIncoming" size="40" color="#85f29f" />
        <AppIcon name="PhoneMissed" size="40" color="#85f29f" />
        <AppIcon name="PhoneOff" size="40" color="#85f29f" />
        <AppIcon name="PhoneOutgoing" size="40" color="#85f29f" />
        <AppIcon name="PieChart" size="40" color="#85f29f" />
        <AppIcon name="Play" size="40" color="#85f29f" />
        <AppIcon name="PlayCircle" size="40" color="#85f29f" />
        <AppIcon name="Plus" size="40" color="#85f29f" />
        <AppIcon name="PlusCircle" size="40" color="#85f29f" />
        <AppIcon name="PlusSquare" size="40" color="#85f29f" />
        <AppIcon name="Pocket" size="40" color="#85f29f" />
        <AppIcon name="Power" size="40" color="#85f29f" />
        <AppIcon name="Printer" size="40" color="#85f29f" />
        <AppIcon name="Radio" size="40" color="#85f29f" />
        <AppIcon name="RefreshCcw" size="40" color="#85f29f" />
        <AppIcon name="RefreshCw" size="40" color="#85f29f" />
        <AppIcon name="Repeat" size="40" color="#85f29f" />
        <AppIcon name="Rewind" size="40" color="#85f29f" />
        <AppIcon name="RotateCcw" size="40" color="#85f29f" />
        <AppIcon name="RotateCw" size="40" color="#85f29f" />
        <AppIcon name="Rss" size="40" color="#85f29f" />
        <AppIcon name="Save" size="40" color="#85f29f" />
        <AppIcon name="Scissors" size="40" color="#85f29f" />
        <AppIcon name="Search" size="40" color="#85f29f" />
        <AppIcon name="Send" size="40" color="#85f29f" />
        <AppIcon name="Server" size="40" color="#85f29f" />
        <AppIcon name="Settings" size="40" color="#85f29f" />
        <AppIcon name="Share" size="40" color="#85f29f" />
        <AppIcon name="Share2" size="40" color="#85f29f" />
        <AppIcon name="Shield" size="40" color="#85f29f" />
        <AppIcon name="ShieldOff" size="40" color="#85f29f" />
        <AppIcon name="ShoppingBag" size="40" color="#85f29f" />
        <AppIcon name="ShoppingCart" size="40" color="#85f29f" />
        <AppIcon name="Shuffle" size="40" color="#85f29f" />
        <AppIcon name="Sidebar" size="40" color="#85f29f" />
        <AppIcon name="SkipBack" size="40" color="#85f29f" />
        <AppIcon name="SkipForward" size="40" color="#85f29f" />
        <AppIcon name="Slack" size="40" color="#85f29f" />
        <AppIcon name="Slash" size="40" color="#85f29f" />
        <AppIcon name="Sliders" size="40" color="#85f29f" />
        <AppIcon name="Smartphone" size="40" color="#85f29f" />
        <AppIcon name="Smile" size="40" color="#85f29f" />
        <AppIcon name="Speaker" size="40" color="#85f29f" />
        <AppIcon name="Square" size="40" color="#85f29f" />
        <AppIcon name="Star" size="40" color="#85f29f" />
        <AppIcon name="StopCircle" size="40" color="#85f29f" />
        <AppIcon name="Sun" size="40" color="#85f29f" />
        <AppIcon name="Sunrise" size="40" color="#85f29f" />
        <AppIcon name="Sunset" size="40" color="#85f29f" />
        <AppIcon name="Tablet" size="40" color="#85f29f" />
        <AppIcon name="Tag" size="40" color="#85f29f" />
        <AppIcon name="Target" size="40" color="#85f29f" />
        <AppIcon name="Terminal" size="40" color="#85f29f" />
        <AppIcon name="Thermometer" size="40" color="#85f29f" />
        <AppIcon name="ThumbsDown" size="40" color="#85f29f" />
        <AppIcon name="ThumbsUp" size="40" color="#85f29f" />
        <AppIcon name="ToggleLeft" size="40" color="#85f29f" />
        <AppIcon name="ToggleRight" size="40" color="#85f29f" />
        <AppIcon name="Tool" size="40" color="#85f29f" />
        <AppIcon name="Trash" size="40" color="#85f29f" />
        <AppIcon name="Trash2" size="40" color="#85f29f" />
        <AppIcon name="Trello" size="40" color="#85f29f" />
        <AppIcon name="TrendingDown" size="40" color="#85f29f" />
        <AppIcon name="TrendingUp" size="40" color="#85f29f" />
        <AppIcon name="Triangle" size="40" color="#85f29f" />
        <AppIcon name="Truck" size="40" color="#85f29f" />
        <AppIcon name="Tv" size="40" color="#85f29f" />
        <AppIcon name="Twitch" size="40" color="#85f29f" />
        <AppIcon name="Twitter" size="40" color="#85f29f" />
        <AppIcon name="Type" size="40" color="#85f29f" />
        <AppIcon name="Umbrella" size="40" color="#85f29f" />
        <AppIcon name="Underline" size="40" color="#85f29f" />
        <AppIcon name="Unlock" size="40" color="#85f29f" />
        <AppIcon name="Upload" size="40" color="#85f29f" />
        <AppIcon name="UploadCloud" size="40" color="#85f29f" />
        <AppIcon name="User" size="40" color="#85f29f" />
        <AppIcon name="UserCheck" size="40" color="#85f29f" />
        <AppIcon name="UserMinus" size="40" color="#85f29f" />
        <AppIcon name="UserPlus" size="40" color="#85f29f" />
        <AppIcon name="UserX" size="40" color="#85f29f" />
        <AppIcon name="Users" size="40" color="#85f29f" />
        <AppIcon name="Video" size="40" color="#85f29f" />
        <AppIcon name="VideoOff" size="40" color="#85f29f" />
        <AppIcon name="Voicemail" size="40" color="#85f29f" />
        <AppIcon name="Volume" size="40" color="#85f29f" />
        <AppIcon name="Volume1" size="40" color="#85f29f" />
        <AppIcon name="Volume2" size="40" color="#85f29f" />
        <AppIcon name="VolumeX" size="40" color="#85f29f" />
        <AppIcon name="Watch" size="40" color="#85f29f" />
        <AppIcon name="Wifi" size="40" color="#85f29f" />
        <AppIcon name="WifiOff" size="40" color="#85f29f" />
        <AppIcon name="Wind" size="40" color="#85f29f" />
        <AppIcon name="X" size="40" color="#85f29f" />
        <AppIcon name="XCircle" size="40" color="#85f29f" />
        <AppIcon name="XSquare" size="40" color="#85f29f" />
        <AppIcon name="Youtube" size="40" color="#85f29f" />
        <AppIcon name="Zap" size="40" color="#85f29f" />
        <AppIcon name="ZapOff" size="40" color="#85f29f" />
        <AppIcon name="ZoomIn" size="40" color="#85f29f" />
        <AppIcon name="ZoomOut" size="40" color="#85f29f" />
    </div>
</template>
<script>

export default {
  name: "IconPage",

};
</script>


<style>
/* Можно добавить стили для сетки или scroll */
</style>